import type { WeatherDashboardPayload, WeatherEvent } from "@/lib/weather/types"

// This local contract fixture keeps the route and explorer usable before the
// independent pipeline has been deployed. It is deliberately labeled in the UI.
export const weatherFixture: WeatherDashboardPayload = {
  schemaVersion: "2.0",
  sourceMode: "fixture",
  generatedAt: "2026-07-09T22:40:27.000Z",
  sourceCoverage: "Local contract fixture. Configure WEATHER_DATA_URL after publishing the dbt artifact.",
  eventCoverage: {
    confirmedThrough: "2024-12-31T23:59:59.000Z",
    preliminaryFrom: null,
    preliminaryThrough: null,
    preliminaryCount: 0,
  },
  eventYearIndex: [
    { year: 2023, count: 1 },
    { year: 2021, count: 1 },
    { year: 2020, count: 1 },
  ],
}

const fixtureEvents: WeatherEvent[] = [
    {
      eventKey: "ncei_storm_events:fixture-al-001",
      eventId: "fixture-al-001",
      regionIds: ["alabama", "dixie"],
      occurredAt: "2023-03-26T17:15:00-05:00",
      state: "AL",
      county: "Houston",
      beginLocation: "West of Dothan",
      endLocation: "Near Columbia",
      ratingCode: "EF2",
      scaleSystem: "EF",
      ratingValue: 2,
      windEstimateLowMph: 111,
      windEstimateHighMph: 135,
      windEstimateNote: "EF-scale three-second gust estimate inferred from damage, not a direct wind measurement.",
      pathLengthMiles: 12.4,
      pathWidthYards: 400,
      beginLatitude: 31.223,
      beginLongitude: -85.49,
      endLatitude: 31.31,
      endLongitude: -85.31,
      injuries: 2,
      fatalities: 0,
      propertyDamageUsd: 2500000,
      cropDamageUsd: null,
      narrative: "Fixture record used to preview the event-detail contract before the published pipeline artifact is configured.",
      sourceUrl: "https://www.ncei.noaa.gov/stormevents/",
      recordStatus: "confirmed",
      sourceSystem: "ncei_storm_events",
      isSurveyedTrack: false,
    },
    {
      eventKey: "ncei_storm_events:fixture-al-002",
      eventId: "fixture-al-002",
      regionIds: ["alabama", "dixie"],
      occurredAt: "2021-03-17T21:42:00-05:00",
      state: "AL",
      county: "Geneva",
      beginLocation: "Southwest of Hartford",
      endLocation: "Northeast of Hartford",
      ratingCode: "EF3",
      scaleSystem: "EF",
      ratingValue: 3,
      windEstimateLowMph: 136,
      windEstimateHighMph: 165,
      windEstimateNote: "EF-scale three-second gust estimate inferred from damage, not a direct wind measurement.",
      pathLengthMiles: 8.7,
      pathWidthYards: 650,
      beginLatitude: 31.07,
      beginLongitude: -85.7,
      endLatitude: 31.16,
      endLongitude: -85.58,
      injuries: 6,
      fatalities: 0,
      propertyDamageUsd: 5200000,
      cropDamageUsd: 150000,
      narrative: "Fixture record used to exercise severe-rating, endpoint, and damage display states.",
      sourceUrl: "https://www.ncei.noaa.gov/stormevents/",
      recordStatus: "confirmed",
      sourceSystem: "ncei_storm_events",
      isSurveyedTrack: false,
    },
    {
      eventKey: "ncei_storm_events:fixture-dixie-001",
      eventId: "fixture-dixie-001",
      regionIds: ["dixie"],
      occurredAt: "2020-04-12T18:10:00-05:00",
      state: "MS",
      county: "Example",
      beginLocation: "Example origin",
      endLocation: "Example endpoint",
      ratingCode: "EF2",
      scaleSystem: "EF",
      ratingValue: 2,
      windEstimateLowMph: 111,
      windEstimateHighMph: 135,
      windEstimateNote: "EF-scale three-second gust estimate inferred from damage, not a direct wind measurement.",
      pathLengthMiles: 19.1,
      pathWidthYards: 450,
      beginLatitude: null,
      beginLongitude: null,
      endLatitude: null,
      endLongitude: null,
      injuries: 1,
      fatalities: 0,
      propertyDamageUsd: null,
      cropDamageUsd: null,
      narrative: "Fixture record without coordinates to verify the unavailable-track state.",
      sourceUrl: "https://www.ncei.noaa.gov/stormevents/",
      recordStatus: "confirmed",
      sourceSystem: "ncei_storm_events",
      isSurveyedTrack: false,
    },
]

export const weatherFixtureEventsByYear: Record<number, WeatherEvent[]> = fixtureEvents.reduce<Record<number, WeatherEvent[]>>(
  (byYear, event) => {
    const year = new Date(event.occurredAt).getFullYear()
    byYear[year] = [...(byYear[year] ?? []), event]
    return byYear
  },
  {},
)
